Real-space cutoffs
dftd4/cpp-d4 pull request #9
Opened 2022-12-12 17:06 UTC by marvinfriede

Real-space cutoffs for the coordination number and the dispersion energy are implemented to (finally) achieve full consistency with the total dispersion energy of the Fortran implementation.

2022-12-12 19:06 UTC, awvwgk requested changes
Let's provide all cutoff values in the constructor rather than having to construct an incomplete object and adding the attributes with setters.

Also, no C-style casting in C++.

2022-12-12 19:17 UTC, marvinfriede commented
> Let's provide all cutoff values in the constructor rather than having to construct an incomplete object and adding the attributes with setters.

I don't understand that part. The constructor writes the default values to all members [here](https://github.com/dftd4/cpp-d4/blob/a705cfd1d3c57447801e63e98a664e8d56bd6a19/src/dftd_cutoff.cpp#L35). The setters are just for changing it (required within a test).
 
> Also, no C-style casting in C++.

So just multiplying by 1.0?

2022-12-12 19:20 UTC, awvwgk commented
> I don't understand that part. The constructor writes the default values to all members [here](https://github.com/dftd4/cpp-d4/blob/a705cfd1d3c57447801e63e98a664e8d56bd6a19/src/dftd_cutoff.cpp#L35). The setters are just for changing it (required within a test).

Why not have the tests recreate the object with the correct values in the constructor then? Or directly setting the value of the members as they are public.

> So just multiplying by 1.0?

https://en.cppreference.com/w/cpp/language/static_cast

2022-12-12 19:27 UTC, marvinfriede commented
> > I don't understand that part. The constructor writes the default values to all members [here](https://github.com/dftd4/cpp-d4/blob/a705cfd1d3c57447801e63e98a664e8d56bd6a19/src/dftd_cutoff.cpp#L35). The setters are just for changing it (required within a test).
> 
> Why not have the tests recreate the object with the correct values in the constructor then? Or directly setting the value of the members as they are public.

Oh. I forgot about the members being public...

2022-12-14 18:59 UTC, awvwgk commented on src/dftd_cutoff.cpp
> +};
Why do we need this function? Also, why the magic number rather than using numeric limits?

2022-12-14 19:14 UTC, marvinfriede commented on src/dftd_cutoff.cpp
> +};
I wrote some tests before implementing the cutoffs. So now it is just a double check to see if the energy is correct with and without using cutoffs. Should I remove the no-cutoff test?

2023-01-04 08:41 UTC, marvinfriede commented
Can I merge this?

2023-01-04 08:48 UTC, awvwgk approved these changes

2023-01-04 08:51 UTC, merged